version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
