# Dockerfile-backend
FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package.json ./
COPY package-lock.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the backend application
COPY . .

# Rename .env.example to .env
RUN mv .env.example .env

# Expose the backend port
EXPOSE 3000

CMD [ "node", "server.js" ]
